# Generated by Django 3.0.7 on 2020-06-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='movieData',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
