# Generated by Django 3.0.7 on 2020-06-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_moviedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='movieData',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
