# Generated by Django 3.0.7 on 2020-06-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200627_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usersURL',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
