# Generated by Django 3.0.7 on 2020-06-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_usersurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usersURL',
        ),
    ]
