# Generated by Django 3.0.7 on 2020-06-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200630_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usersURL',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
