# Generated by Django 3.0.7 on 2020-06-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_usersurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usersURL',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
