# Generated by Django 3.0.7 on 2020-06-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200630_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usersURL',
            field=models.CharField(max_length=5000),
        ),
    ]
