# Generated by Django 3.0.7 on 2020-06-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
    ]
