# Generated by Django 3.0.7 on 2020-06-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200625_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
