# Generated by Django 3.0.7 on 2020-06-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200629_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='IMDBScore',
            field=models.FloatField(),
        ),
    ]
